const foodItems = [
    {
        id: 1,
        name: "Ambur Biryani",
        category: "biryani",
        rating: 4.3,
        price: 13,
        img: "images/biryani/Ambur-Chicken-Biryani.jpg",
    },
    {
        id: 2,
        name: "Hyderabadi Biryani",
        category: "biryani",
        rating: 4.3,
        price: 15,
        img: "images/biryani/Chicken-Biryani-hyd.jpg",
    },
    {
        id: 3,
        name: "Egg Biryani",
        category: "biryani",
        rating: 4.3,
        price: 18,
        img: "images/biryani/egg-biryani.jpeg",
    },
    {
        id: 4,
        name: "Goan Fish Biryani",
        category: "biryani",
        rating: 4.3,
        price: 15,
        img: "images/biryani/goan-fish-biryani.jpg",
    },
    {
        id: 5,
        name: "Mutton Biryani",
        category: "biryani",
        rating: 4.3,
        price: 10,
        img: "images/biryani/hyd-Mutton-Biryani.jpg",
    },
    {
        id: 6,
        name: "Kamrupi Biryani",
        category: "biryani",
        rating: 4.3,
        price: 12,
        img: "images/biryani/kamrupi-biryani.jpg",
    },
    {
        id: 7,
        name: "Kashmiri Biryani",
        category: "biryani",
        rating: 4.3,
        price: 13,
        img: "images/biryani/kashmiri.pulao.jpg",
    },
    {
        id: 8,
        name: "Memoni Biryani",
        category: "biryani",
        rating: 4.3,
        price: 20,
        img: "images/biryani/memonibiryani.png",
    },
    {
        id: 9,
        name: "Mughlai Biryani",
        category: "biryani",
        rating: 4.3,
        price: 15,
        img: "images/biryani/mughlai-biryani.jpg",
    },
    {
        id: 10,
        name: "Chicken Roast",
        category: "chicken",
        rating: 4.3,
        price: 11,
        img: "images/chicken/Chicken_roast.jpg",
    },
    {
        id: 11,
        name: "Chicken Curry",
        category: "chicken",
        rating: 4.3,
        price: 10,
        img: "images/chicken/Chicken-Curry.jpg",
    },
    {
        id: 12,
        name: "Chicken Do Pyaza",
        category: "chicken",
        rating: 4.3,
        price: 14,
        img: "images/chicken/Chicken-do-Pyaza.jpg",
    },
    {
        id: 13,
        name: "Chicken Masala",
        category: "chicken",
        rating: 4.3,
        price: 12,
        img: "images/chicken/Chicken-Masala.jpeg",
    },
    {
        id: 14,
        name: "Handi Chicken",
        category: "chicken",
        rating: 4.3,
        price: 17,
        img: "images/chicken/Handi-chicken.jpg",
    },
    {
        id: 15,
        name: "Murgh Musallam",
        category: "chicken",
        rating: 4.3,
        price: 20,
        img: "images/chicken/Murgh-Musallam.jpg",
    },
    {
        id: 16,
        name: "Matar Paneer",
        category: "paneer",
        rating: 4.3,
        price: 15,
        img: "images/paneer/Matar-Paneer.jpg",
    },
    {
        id: 17,
        name: "Palak Paneer",
        category: "paneer",
        rating: 4.3,
        price: 10,
        img: "images/paneer/palak-paneer.jpg",
    },
    {
        id: 18,
        name: "Paneer Butter Masala",
        category: "paneer",
        rating: 4.3,
        price: 15,
        img: "images/paneer/paneer-butter-masala.jpg",
    },
    {
        id: 19,
        name: "Paneer Do Pyaza",
        category: "paneer",
        rating: 4.3,
        price: 12,
        img: "images/paneer/Paneer-Do-Pyaza.jpg",
    },
    {
        id: 20,
        name: "Hyderabadi Paneer",
        category: "paneer",
        rating: 4.3,
        price: 8,
        img: "images/paneer/Paneer-Hyderabadi.jpg",
    },
    {
        id: 21,
        name: "Paneer Lababdar",
        category: "paneer",
        rating: 4.3,
        price: 7,
        img: "images/paneer/paneer-lababdar.jpg",
    },
    {
        id: 22,
        name: "Shahi Paneer",
        age: "32",
        category: "paneer",
        rating: 4.3,
        price: 5,
        img: "images/paneer/shahi-paneer.jpg",
    },
    {
        id: 23,
        name: "Navratan Korma",
        category: "vegetable",
        rating: 4.3,
        price: 8,
        img: "images/vegetable/navratan-korma_-vegetable.png",
    },
    {
        id: 24,
        name: "Veg Jalfrezi",
        category: "vegetable",
        rating: 4.3,
        price: 7,
        img: "images/vegetable/VEG-JALFREZI.jpg",
    },
    {
        id: 25,
        name: "Veg Biryani",
        category: "vegetable",
        rating: 4.3,
        price: 5,
        img: "images/vegetable/vegetable-biryani.jpg",
    },
    {
        id: 26,
        name: "Veg Curry",
        category: "vegetable",
        rating: 4.3,
        price: 7,
        img: "images/vegetable/vegetable-curry.jpeg",
    },
    {
        id: 27,
        name: "Veg Kolhapur",
        category: "vegetable",
        rating: 4.3,
        price: 10,
        img: "images/vegetable/vegetable-kolhapuri.jpg",
    },
    {
        id: 28,
        name: "Veg Masala",
        category: "vegetable",
        rating: 4.3,
        price: 4,
        img: "images/vegetable/vegetable-masala.jpg",
    },
    {
        id: 29,
        name: "Veg Pakora",
        category: "vegetable",
        rating: 4.3,
        price: 4,
        img: "images/vegetable/vegetable-pakora.jpg",
    },
    {
        id: 30,
        name: "Momos",
        category: "chinese",
        rating: 4.3,
        price: 8,
        img: "images/chinese/cabbage-momos-.jpg",
    },
    {
        id: 31,
        name: "Chicken Manchurian",
        category: "chinese",
        rating: 4.3,
        price: 7,
        img: "images/chinese/ChickenManchurian.jpg",
    },
    {
        id: 32,
        name: "Chili Chicken",
        category: "chinese",
        rating: 4.3,
        price: 5,
        img: "images/chinese/Chili-Chicken.jpg",
    },
    {
        id: 33,
        name: "Chowmein",
        category: "chinese",
        rating: 4.3,
        price: 16,
        img: "images/chinese/chowmin.jpg",
    },
    {
        id: 34,
        name: "Spring Roll",
        category: "chinese",
        rating: 4.3,
        price: 14,
        img: "images/chinese/spring-rolls.jpg",
    },
    {
        id: 35,
        name: "Szechuan Chicken",
        category: "chinese",
        rating: 4.3,
        price: 10,
        img: "images/chinese/szechuan-chicken.jpg",
    },
    {
        id: 36,
        name: "Fried Rice",
        category: "chinese",
        rating: 4.3,
        price: 8,
        img: "images/chinese/veg-fried-rice.jpg",
    },
    {
        id: 37,
        name: "Butter Masala Dosa",
        category: "south indian",
        rating: 4.3,
        price: 18,
        img: "images/south indian/Butter-Masala-Dosa.png",
    },
    {
        id: 38,
        name: "Idli",
        category: "south indian",
        rating: 4.3,
        price: 20,
        img: "images/south indian/idli-with-rice-flour.jpg",
    },
    {
        id: 39,
        name: "Masala Dosa",
        category: "south indian",
        rating: 4.3,
        price: 12,
        img: "images/south indian/masala-dosa.jpg",
    },
    {
        id: 40,
        name: "Mysore Bonda",
        category: "south indian",
        rating: 4.3,
        price: 10,
        img: "images/south indian/mysore-bonda.jpg",
    },
    {
        id: 41,
        name: "Onion Uttapam",
        category: "south indian",
        rating: 4.3,
        price: 15,
        img: "images/south indian/onion-uttapam.jpg",
    },
    {
        id: 42,
        name: "Plain Dosa",
        category: "south indian",
        rating: 4.3,
        price: 40,
        img: "images/south indian/plain-dosa.jpeg",
    },
    {
        id: 43,
        name: "Rava Uttapam",
        category: "south indian",
        rating: 4.3,
        price: 25,
        img: "images/south indian/Rava-Uttapam.jpg",
    },
    {
        id: 44,
        name: "Sambhar Vada",
        category: "south indian",
        rating: 4.3,
        price: 34,
        img: "images/south indian/sambhar-vada.jpg",
    },
];

export { foodItems };